version: 2.1

defaults: &defaults
  docker: 
    - image: cimg/node:lts
  working_directory: ~/project

jobs:
  build:
    << : *defaults
    steps:
      - checkout
      - run:
          name: install node
          command: npm i 
      - run:
          name: build app
          command: npm run lint
      - save_cache:
          key: "node_files"
          paths: 
            - /src/node_modules
  test:
    << : *defaults
    steps:
      - checkout
      - restore_cache:
          kees:
            - "node_files"
      - run:
          name: test app
          command: npm run test
  analyze:
    << : *defaults
    steps:
      - checkout
      - run:
          name: analyze app
          command: npm audit

workflows:
  default:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test

  
